services:
  reverse-proxy:
    image: nginx
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - docs:/var/www/docs
    ports:
      - "80:80"
    networks:
      - hsjs
volumes:
  docs:
    external: true
networks:
  hsjs:
    external: true
