services:
  reverse-proxy:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    networks:
      - registry_default
      - docs_default
networks:
  registry_default:
    external: true
  docs_default:
    external: true
