services:
  docs:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 3001:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - docs:/var/www/docs
    networks:
      - hsjs
networks:
  hsjs:
    name: hsjs
volumes:
  docs:
    name: docs
